version: "3"

services:
  exercises_db:
    image: "mongo:latest"
    container_name: "exercises_db"
    restart: "always"
    env_file:
      - .env
    volumes:
      #   - ./services/exercises_db/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
      - ./services/exercises_db/mongo_volume:/data/db
    ports:
      - "27017-27019:27017-27019"
