version: "3"

services:
  auth:
    command: ["npm", "run", "start:dev"]
  # exercises_service:
  #   environment:
  #     - TEST=TESTinDEVMODEYOLOooo
  #   restart: "no"
  #   volumes:
  #     - ./services/exercises:/app
  #   command: ["npm", "run", "start"]
