version: "3"

services:
  auth:
    volumes:
      - ./services/auth:/app
      - container_node_modules:/app/node_modules
    command: ["npm", "run", "start:dev"]
  # exercises_service:
  #   environment:
  #     - TEST=TESTinDEVMODEYOLOooo
  #   restart: "no"
  #   volumes:
  #     - ./services/exercises:/app
  #   command: ["npm", "run", "start"]
volumes:
  container_node_modules:
