version: "3"

services:
  auth_db:
    image: postgres
    container_name: auth_db
    restart: always
    hostname: "auth_db"
    volumes:
      - ./services/auth_db/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"

  auth:
    container_name: auth_service
    env_file:
      - .env
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    restart: "always"
    ports:
      - "7000:7000"
